name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/DevOps-CI-CD-project
            git pull origin main
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true
            docker build -t my-node-app .
            docker run -d -p 3000:3000 my-node-app
